CoffeeShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app_shop.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_shop/urls.py
from django.urls import path
from app_shop.views import *

app_name = 'app_shop'
urlpatterns = [
    path('', trang_chu, name='trang-chu'),
    path('gioi-thieu/',gioi_thieu, name='gioi-thieu'),
    path('lien-he/', lien_he, name='lien-he'),
    path('dang-ky/', dang_ky, name='dang-ky'),
    path('danh-muc/<int:danh_muc_id>/', danh_sach_san_pham, name='danh-sach-san-pham'),
]

app_shop/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Category (models.Model) :
    name = models.CharField(max_length=225)
    description = models.TextField(null=True, blank=True)
    def __str__(self) -> str:
        return self.name

class Product(models.Model) :
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models. CharField(max_length=225)
    description = models.TextField(null=True, blank=True)
    price = models.IntegerField(default=0)
    image = models.ImageField(upload_to='images/products')
    publish_date = models.DateTimeField(default=timezone.now)
    def __str__(self) -> str:
       return self.name
    

class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(null=True)
    subject = models.CharField(max_length=250,null=True)
    message = models.TextField(null=True)
    created = models.DateTimeField(default=timezone.now,null=True)
    def __str__(self) -> str:
        return self.name
    
class Member(models.Model):
    name = models.CharField(max_length=100,null=True)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=200,null=True)
    avatar = models.ImageField(upload_to='images/avatars', default='images/avatars/noavatar.png')
    created = models.DateTimeField(default=timezone.now,null=True)
    def __str__(self) -> str:
        return self.name
    

app_shop/views.py
from django.shortcuts import render, HttpResponse
from datetime import datetime
from app_shop.models import Category, Product, Contact
from app_shop.form import ContactForm

# Create your views here.
ds_danh_muc = Category.objects.all()
def trang_chu(request):
    return render(request,'index.html', {
        'ds_danh_muc':ds_danh_muc,
    })

def gioi_thieu(request):
    return render(request,'about.html', {
        'ds_danh_muc':ds_danh_muc,
    })

def lien_he(request):
    form_lienhe = ContactForm()
    thong_bao = ''
    if request.GET.get('name'):
        ho_ten = request.GET.get('name')
        email = request.GET.get('email')
        tieu_de = request.GET.get('subject')
        message = request.GET.get('message')
        Contact.objects.create(name=ho_ten, email=email, subject=tieu_de, message= message)
        
        #thông báo kết quả
        thong_bao = '''<div class="alert alert-success" role="alert">
                    Đã gửi thông tin thành công!!!!
                    </div>'''

    return render(request,'contact.html', {
        'ds_danh_muc':ds_danh_muc,
        'form_lien_he': form_lienhe,
        'thong_bao': thong_bao,
    })

def dang_ky(request):
    form_lienhe = ContactForm()
    thong_bao = ''
    if request.GET.get('name'):
        ho_ten = request.GET.get('name')
        email = request.GET.get('email')
        tieu_de = request.GET.get('subject')
        message = request.GET.get('message')
        Contact.objects.create(name=ho_ten, email=email, subject=tieu_de, message= message)
        
        #thông báo kết quả
        thong_bao = '''<div class="alert alert-success" role="alert">
                    Đã gửi thông tin thành công!!!!
                    </div>'''

    return render(request,'contact.html', {
        'ds_danh_muc':ds_danh_muc,
        'form_lien_he': form_lienhe,
        'thong_bao': thong_bao,
    })

def danh_sach_san_pham(request,danh_muc_id):
    danh_muc = Category.objects.get(id=danh_muc_id)
    ds_san_pham = Product.objects.filter(category_id=danh_muc_id)
    return render(request,'category.html', {
        'ds_danh_muc':ds_danh_muc,
        'danh_muc01':danh_muc,
        'ds_san_pham':ds_san_pham,
    })

templates/_Base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!---->
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Oswald:wght@500;600;700&family=Pacifico&display=swap" rel="stylesheet"> 

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid px-0 d-none d-lg-block">
        <div class="row gx-0">
            <div class="col-lg-4 text-center bg-secondary py-3">
                <div class="d-inline-flex align-items-center justify-content-center">
                    <i class="bi bi-envelope fs-1 text-primary me-3"></i>
                    <div class="text-start">
                        <h6 class="text-uppercase mb-1">Email</h6>
                        <span>nnlg9214@gmail.com</span>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 text-center bg-primary border-inner py-3">
                <div class="d-inline-flex align-items-center justify-content-center">
                    <a href="/" class="navbar-brand">
                        <h1 class="m-0 text-uppercase text-white"><i class="fas fa-mug-hot fs-1 text-dark me-3"></i>CoffeeShop</h1>
                    </a>
                </div>
            </div>
            <div class="col-lg-4 text-center bg-secondary py-3">
                <div class="d-inline-flex align-items-center justify-content-center">
                    <i class="bi bi-phone-vibrate fs-1 text-primary me-3"></i>
                    <div class="text-start">
                        <h6 class="text-uppercase mb-1">Gọi ngay</h6>
                        <span>0932.745.xxx</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->
    
    <!-- Navbar Start -->
    {% include 'parts/menu.html' %}
    <!-- Navbar End -->

    <!-- Content Start -->
    {% block content %}{% endblock%}
    <!-- Content End -->


    <!-- Footer Start -->
    {% include 'parts/footer.html' %}
    <!-- Footer End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-primary border-inner py-3 fs-4 back-to-top"><i class="bi bi-arrow-up"></i></a>

        <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/category.html
{% extends '_Base.html' %}
{% load humanize %}
{% load static %}
    {% block title %}
        CoffeeShop® - {{danh_muc01.name}}
    {% endblock %}

    {% block content %}
    <!-- Page Header Start -->
    <div class="container-fluid bg-dark bg-img p-5 mb-5">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="display-4 text-uppercase text-white">{{danh_muc01.name}}</h1>
                <a href="/">Trang chủ</a>
                <i class="far fa-square text-primary px-2"></i>
                <a href="/danh-muc/{{danh_muc01.id}}/">{{danh_muc01.name}}</a>
            </div>
        </div>
    </div>
    <!-- Page Header End -->

    <!-- Products Start -->
    <div class="container-fluid about py-5">
        <div class="container">
            <div class="section-title position-relative text-center mx-auto mb-5 pb-3" style="max-width: 600px;">
                <h2 class="text-primary font-secondary">Thực đơn</h2>
                <h1 class="display-4 text-uppercase">{{danh_muc01.name}}</h1>
            </div>
            <div class="tab-class text-center">
                <div class="tab-content">
                    <div id="tab-1" class="tab-pane fade show p-0 active">
                        <div class="row g-3">
                            {% for san_pham in ds_san_pham %}
                            <div class="col-lg-6">
                                <div class="d-flex h-100">
                                    <div class="flex-shrink-0">
                                        <img class="img-fluid" src="/media/{{san_pham.image|safe}}" alt="" style="width: 150px;" data-bs-toggle="modal" data-bs-target="#sp{{san_pham.id}}">
                                        <h4 class="bg-dark text-primary p-2 m-0">{{san_pham.price}}</h4>
                                    </div>
                                    <div class="d-flex flex-column justify-content-center text-start bg-secondary border-inner px-4">
                                        <h5 class="text-uppercase" data-bs-toggle="modal" data-bs-target="#sp{{san_pham.id}}">{{san_pham.name}}</h5>
                                        <span>{{san_pham.description|truncatewords:40}}</span>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Products End -->
    {% for san_pham in ds_san_pham %}
    <!-- Modal -->
    <div class="modal fade" id="sp{{san_pham.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg ">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5 text-uppercase" id="exampleModalLabel">{{san_pham.name}}</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="flex-shrink-0 float-start">
                        <img class="img-fluid me-4" src="/media/{{san_pham.image|safe}}" alt="" style="width: 240px;">
                    </div>
                    <div class="d-flex flex-column justify-content-center text-start">
                        <h5 class="text-uppercase">{{san_pham.name}}</h5>
                        <h4 class="text-primary">{{san_pham.price|intcomma}} VND</h4>
                        <span>{{san_pham.description}}</span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">ĐÓNG</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal END-->
    {% endfor %}
    

    {% endblock %}

templates/contact.html
{% extends '_Base.html' %}
{% load static %}

    {% block title %}
        CoffeeShop® - Liên hệ
    {% endblock %}

    {% block content %}

    <!-- Page Header Start -->
    <div class="container-fluid bg-dark bg-img p-5 mb-5">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="display-4 text-uppercase text-white">Liên hệ</h1>
                <a href="">Trang chủ</a>
                <i class="far fa-square text-primary px-2"></i>
                <a href="">Liên hệ</a>
            </div>
        </div>
    </div>
    <!-- Page Header End -->

    
    <!-- Contact Start -->
    <div class="container-fluid contact position-relative px-5" style="margin-top: 90px;">
        <div class="container">
            <div class="row g-5 mb-5">
                <div class="col-lg-4 col-md-6">
                    <div class="bg-primary border-inner text-center text-white p-5">
                        <i class="bi bi-geo-alt fs-1 text-white"></i>
                        <h6 class="text-uppercase my-2">Văn phòng</h6>
                        <span>227 Nguyễn Văn Cừ, P4, Q5</span>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="bg-primary border-inner text-center text-white p-5">
                        <i class="bi bi-envelope-open fs-1 text-white"></i>
                        <h6 class="text-uppercase my-2">Email</h6>
                        <span>nnlg9214@gmail.com</span>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="bg-primary border-inner text-center text-white p-5">
                        <i class="bi bi-phone-vibrate fs-1 text-white"></i>
                        <h6 class="text-uppercase my-2">Gọi ngay</h6>
                        <span>0932.745.xxx</span>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <form method="get">
                        <div class="row g-3">
                            <div class="col-sm-12">
                                {{ thong_bao|safe }}
                            </div>
                            <div class="col-sm-6">
                                {{ form_lien_he.name }}
                            </div>
                            <div class="col-sm-6">
                                {{ form_lien_he.email }}
                            </div>
                            <div class="col-sm-12">
                                {{ form_lien_he.subject }}
                            </div>
                            <div class="col-sm-12">
                                {{ form_lien_he.message }}
                            </div>
                            <div class="col-sm-12">
                                <button class="btn btn-primary border-inner w-100 py-3" type="submit">Gửi thông tin</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->


    {% endblock %}

templates/contact_bk.html
{% extends '_Base.html' %}
{% load static %}

    {% block title %}
        CoffeeShop® - Liên hệ
    {% endblock %}

    {% block content %}

    <!-- Page Header Start -->
    <div class="container-fluid bg-dark bg-img p-5 mb-5">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="display-4 text-uppercase text-white">Liên hệ</h1>
                <a href="">Trang chủ</a>
                <i class="far fa-square text-primary px-2"></i>
                <a href="">Liên hệ</a>
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Contact Start -->
    <div class="container-fluid contact position-relative px-5" style="margin-top: 90px;">
        <div class="container">
            <div class="row g-5 mb-5">
                <div class="col-lg-4 col-md-6">
                    <div class="bg-primary border-inner text-center text-white p-5">
                        <i class="bi bi-geo-alt fs-1 text-white"></i>
                        <h6 class="text-uppercase my-2">Văn phòng</h6>
                        <span>227 Nguyễn Văn Cừ, P4, Q5</span>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="bg-primary border-inner text-center text-white p-5">
                        <i class="bi bi-envelope-open fs-1 text-white"></i>
                        <h6 class="text-uppercase my-2">Email</h6>
                        <span>nnlg9214@gmail.com</span>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="bg-primary border-inner text-center text-white p-5">
                        <i class="bi bi-phone-vibrate fs-1 text-white"></i>
                        <h6 class="text-uppercase my-2">Gọi ngay</h6>
                        <span>0932.745.xxx</span>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <form>
                        <div class="row g-3">
                            <div class="col-sm-6">
                                <input type="text" class="form-control bg-light border-0 px-4" placeholder="Họ tên" style="height: 55px;">
                            </div>
                            <div class="col-sm-6">
                                <input type="email" class="form-control bg-light border-0 px-4" placeholder="Email" style="height: 55px;">
                            </div>
                            <div class="col-sm-12">
                                <input type="text" class="form-control bg-light border-0 px-4" placeholder="Tiêu đề" style="height: 55px;">
                            </div>
                            <div class="col-sm-12">
                                <textarea class="form-control bg-light border-0 px-4 py-3" rows="4" placeholder="Nội dung"></textarea>
                            </div>
                            <div class="col-sm-12">
                                <button class="btn btn-primary border-inner w-100 py-3" type="submit">Gửi thông tin</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->


    {% endblock %}

templates/old/demo_dtl.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django Template Language demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
  </head>
  <body>
    

    <div class="container">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#"><img alt="Logo" src="{% static 'images/logo.png' %}"/></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Dropdown
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                        </li>
                    </ul>
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" />
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
        <hr>
        <div class="float-end">{{ now|date:'d-m-Y H:i:s' }}</div>
        <h1>Danh sách sinh viên ({{ dssv02|length }})</h1>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Mã SV</th>
                    <th scope="col">Họ tên</th>
                    <th scope="col">Địa chỉ</th>
                </tr>
            </thead>
            <tbody>
                {% for sv in dssv02 %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{sv.ma_sv}}</td>
                    <td>{{sv.ho_ten}}</td>
                    <td>{{sv.dia_chi}}</td>
                </tr>
                {% endfor %}
                
            </tbody>
        </table>
        <hr>
        {{ nd|upper}}
        <hr>
        {{ nd|truncatewords:50}}
        <hr>
        {{ nd|truncatechars:50}}

        <hr>
        {{ tb|safe }}

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
  </body>
</html>

templates/old/lib.html
{% load static %}
    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>

templates/parts/footer.html
<div class="container-fluid bg-img text-secondary" style="margin-top: 90px">
        <div class="container">
            <div class="row gx-5">
                <div class="col-lg-4 col-md-6 mb-lg-n5">
                    <div class="d-flex flex-column align-items-center justify-content-center text-center h-100 bg-primary border-inner p-4">
                        <a href="{% url 'app_shop:trang-chu' %}" class="navbar-brand">
                            <h1 class="m-0 text-uppercase text-white"><i class="fas fa-mug-hot fs-1 text-dark me-3"></i>CoffeeShop</h1>
                        </a>
                        <p class="mt-3">CoffeeShop® được thành lập vào năm 1999, bắt nguồn từ tình yêu dành cho đất Việt cùng với cà phê và cộng đồng nơi đây. Ngay từ những ngày đầu tiên, mục tiêu của chúng mình là có thể phục vụ và góp phần phát triển cộng đồng bằng cách siết chặt thêm sự kết nối và sự gắn bó giữa người với người.</p>
                    </div>
                </div>
                <div class="col-lg-8 col-md-6">
                    <div class="row gx-5">
                        <div class="col-lg-4 col-md-12 pt-5 mb-5">
                            <h4 class="text-primary text-uppercase mb-4">Thông Tin Liên Hệ</h4>
                            <div class="d-flex mb-2">
                                <i class="bi bi-geo-alt text-primary me-2"></i>
                                <p class="mb-0">227 Nguyễn Văn Cừ, P4, Q5</p>
                            </div>
                            <div class="d-flex mb-2">
                                <i class="bi bi-envelope-open text-primary me-2"></i>
                                <p class="mb-0">nnlg92142@gmail.com</p>
                            </div>
                            <div class="d-flex mb-2">
                                <i class="bi bi-telephone text-primary me-2"></i>
                                <p class="mb-0">0932.745.xxx</p>
                            </div>
                            <div class="d-flex mt-4">
                                <a class="btn btn-lg btn-primary btn-lg-square border-inner rounded-0 me-2" href="#"><i class="fab fa-twitter fw-normal"></i></a>
                                <a class="btn btn-lg btn-primary btn-lg-square border-inner rounded-0 me-2" href="#"><i class="fab fa-facebook-f fw-normal"></i></a>
                                <a class="btn btn-lg btn-primary btn-lg-square border-inner rounded-0 me-2" href="#"><i class="fab fa-linkedin-in fw-normal"></i></a>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-12 pt-0 pt-lg-5 mb-5">
                            <h4 class="text-primary text-uppercase mb-4">Thông Tin Cửa Hàng</h4>
                            <div class="d-flex flex-column justify-content-start">
                                <a class="text-secondary mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Thẻ</a>
                                <a class="text-secondary mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Đối tác</a>
                                <a class="text-secondary mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Danh sách cửa hàng</a>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-12 pt-0 pt-lg-5 mb-5">
                            <h4 class="text-primary text-uppercase mb-4">Nhận Thông Tin</h4>
                            <p>Đăng ký để nhận thông tin từ chúng tôi</p>
                            <form action="">
                                <div class="input-group">
                                    <input type="text" class="form-control border-white p-3" placeholder="Nhập địa chỉ Email">
                                    <button class="btn btn-primary">Đăng ký</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid text-secondary py-4" style="background: #111111;">
        <div class="container text-center">
            <p class="mb-0">&copy; <a class="text-white border-bottom" href="/">CoffeeShop</a>. All Rights Reserved. 
			
			<!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
			Designed by <a class="text-white border-bottom" href="https://htmlcodex.com">HTML Codex</a></p>
        </div>
    </div>

templates/parts/menu.html
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark shadow-sm py-3 py-lg-0 px-3 px-lg-0">
        <a href="{% url 'app_shop:trang-chu' %}" class="navbar-brand d-block d-lg-none">
            <h1 class="m-0 text-uppercase text-white"><i class="fas fa-mug-hot fs-1 text-primary me-3"></i>CoffeeShop</h1>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto mx-lg-auto py-0">
                <a href="{% url 'app_shop:trang-chu' %}" class="nav-item nav-link active">Trang chủ</a>
                <a href="{% url 'app_shop:gioi-thieu' %}" class="nav-item nav-link">Giới thiệu</a>
                <a href="/" class="nav-item nav-link">Tin tức</a>
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Sản phẩm</a>
                    <div class="dropdown-menu m-0">
                        {%for danh_muc in ds_danh_muc %}
                            <a href="{% url 'app_shop:danh-sach-san-pham' danh_muc_id=danh_muc.id %}" class="dropdown-item">{{danh_muc.name}}</a>
                        {% endfor %}
                    </div>
                </div>
                <a href="{% url 'app_shop:lien-he' %}" class="nav-item nav-link">Liên hệ</a>
                <a href="{% url 'app_shop:dang-ky' %}" class="nav-item nav-link">Đăng ký</a>
            </div>
        </div>
    </nav>